/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorsRouteImport } from './routes/investors'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as AuthTestRouteImport } from './routes/auth-test'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks.$taskId'
import { Route as ProfileSlugRouteImport } from './routes/profile.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRunnerDashboardRouteImport } from './routes/_authenticated/runner-dashboard'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedInvestorDashboardRouteImport } from './routes/_authenticated/investor-dashboard'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedDisputesRouteImport } from './routes/_authenticated/disputes'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin-dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAcademyRouteImport } from './routes/_authenticated/academy'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAcademyIndexRouteImport } from './routes/_authenticated/academy.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as AuthenticatedSettingsSupportRouteImport } from './routes/_authenticated/settings.support'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsPrivacyRouteImport } from './routes/_authenticated/settings.privacy'
import { Route as AuthenticatedSettingsPreferencesRouteImport } from './routes/_authenticated/settings.preferences'
import { Route as AuthenticatedSettingsPaymentsRouteImport } from './routes/_authenticated/settings.payments'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings.notifications'
import { Route as AuthenticatedSettingsAdminRouteImport } from './routes/_authenticated/settings.admin'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedProfileVerificationRouteImport } from './routes/_authenticated/profile.verification'
import { Route as AuthenticatedProfileIdVerificationRouteImport } from './routes/_authenticated/profile.id-verification'
import { Route as AuthenticatedProfileEditRouteImport } from './routes/_authenticated/profile.edit'
import { Route as AuthenticatedProfileBackgroundCheckRouteImport } from './routes/_authenticated/profile.background-check'
import { Route as AuthenticatedMessagesNewRouteImport } from './routes/_authenticated/messages.new'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedDashboardRunnerRouteImport } from './routes/_authenticated/dashboard.runner'
import { Route as AuthenticatedDashboardInvestorRouteImport } from './routes/_authenticated/dashboard.investor'
import { Route as AuthenticatedDashboardFavoritesRouteImport } from './routes/_authenticated/dashboard.favorites'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedAdminRunnerApprovalsRouteImport } from './routes/_authenticated/admin.runner-approvals'
import { Route as AuthenticatedAdminProfilesRouteImport } from './routes/_authenticated/admin.profiles'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin.moderation'
import { Route as AuthenticatedAdminMarketplaceHealthRouteImport } from './routes/_authenticated/admin.marketplace-health'
import { Route as AuthenticatedAdminDispatchRouteImport } from './routes/_authenticated/admin.dispatch'
import { Route as AuthenticatedAdminBroadcastsRouteImport } from './routes/_authenticated/admin.broadcasts'
import { Route as AuthenticatedAdminBackgroundChecksRouteImport } from './routes/_authenticated/admin.background-checks'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAcademyCourseSlugRouteImport } from './routes/_authenticated/academy.$courseSlug'
import { Route as AuthenticatedAcademyCourseSlugIndexRouteImport } from './routes/_authenticated/academy.$courseSlug.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedAcademyCourseSlugQuizRouteImport } from './routes/_authenticated/academy.$courseSlug.quiz'
import { Route as AuthenticatedAcademyCourseSlugCertificateRouteImport } from './routes/_authenticated/academy.$courseSlug.certificate'
import { Route as AuthenticatedAcademyCourseSlugLessonSlugRouteImport } from './routes/_authenticated/academy.$courseSlug.$lessonSlug'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorsRoute = InvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth-test',
  path: '/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => TasksRoute,
} as any)
const ProfileSlugRoute = ProfileSlugRouteImport.update({
  id: '/profile/$slug',
  path: '/profile/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunnerDashboardRoute =
  AuthenticatedRunnerDashboardRouteImport.update({
    id: '/runner-dashboard',
    path: '/runner-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvestorDashboardRoute =
  AuthenticatedInvestorDashboardRouteImport.update({
    id: '/investor-dashboard',
    path: '/investor-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDisputesRoute = AuthenticatedDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin-dashboard',
    path: '/admin-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAcademyRoute = AuthenticatedAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAcademyIndexRoute =
  AuthenticatedAcademyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAcademyRoute,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsSupportRoute =
  AuthenticatedSettingsSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPrivacyRoute =
  AuthenticatedSettingsPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPreferencesRoute =
  AuthenticatedSettingsPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPaymentsRoute =
  AuthenticatedSettingsPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAdminRoute =
  AuthenticatedSettingsAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedProfileVerificationRoute =
  AuthenticatedProfileVerificationRouteImport.update({
    id: '/profile/verification',
    path: '/profile/verification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIdVerificationRoute =
  AuthenticatedProfileIdVerificationRouteImport.update({
    id: '/profile/id-verification',
    path: '/profile/id-verification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileEditRoute =
  AuthenticatedProfileEditRouteImport.update({
    id: '/profile/edit',
    path: '/profile/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileBackgroundCheckRoute =
  AuthenticatedProfileBackgroundCheckRouteImport.update({
    id: '/profile/background-check',
    path: '/profile/background-check',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesNewRoute =
  AuthenticatedMessagesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedMessagesRoute,
  } as any)
const AuthenticatedDashboardRunnerRoute =
  AuthenticatedDashboardRunnerRouteImport.update({
    id: '/dashboard/runner',
    path: '/dashboard/runner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardInvestorRoute =
  AuthenticatedDashboardInvestorRouteImport.update({
    id: '/dashboard/investor',
    path: '/dashboard/investor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardFavoritesRoute =
  AuthenticatedDashboardFavoritesRouteImport.update({
    id: '/dashboard/favorites',
    path: '/dashboard/favorites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRunnerApprovalsRoute =
  AuthenticatedAdminRunnerApprovalsRouteImport.update({
    id: '/runner-approvals',
    path: '/runner-approvals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfilesRoute =
  AuthenticatedAdminProfilesRouteImport.update({
    id: '/profiles',
    path: '/profiles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMarketplaceHealthRoute =
  AuthenticatedAdminMarketplaceHealthRouteImport.update({
    id: '/marketplace-health',
    path: '/marketplace-health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDispatchRoute =
  AuthenticatedAdminDispatchRouteImport.update({
    id: '/dispatch',
    path: '/dispatch',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBroadcastsRoute =
  AuthenticatedAdminBroadcastsRouteImport.update({
    id: '/broadcasts',
    path: '/broadcasts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBackgroundChecksRoute =
  AuthenticatedAdminBackgroundChecksRouteImport.update({
    id: '/background-checks',
    path: '/background-checks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAcademyCourseSlugRoute =
  AuthenticatedAcademyCourseSlugRouteImport.update({
    id: '/$courseSlug',
    path: '/$courseSlug',
    getParentRoute: () => AuthenticatedAcademyRoute,
  } as any)
const AuthenticatedAcademyCourseSlugIndexRoute =
  AuthenticatedAcademyCourseSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAcademyCourseSlugRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAcademyCourseSlugQuizRoute =
  AuthenticatedAcademyCourseSlugQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => AuthenticatedAcademyCourseSlugRoute,
  } as any)
const AuthenticatedAcademyCourseSlugCertificateRoute =
  AuthenticatedAcademyCourseSlugCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthenticatedAcademyCourseSlugRoute,
  } as any)
const AuthenticatedAcademyCourseSlugLessonSlugRoute =
  AuthenticatedAcademyCourseSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => AuthenticatedAcademyCourseSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/apply': typeof ApplyRoute
  '/auth-test': typeof AuthTestRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRouteWithChildren
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/academy': typeof AuthenticatedAcademyRouteWithChildren
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/disputes': typeof AuthenticatedDisputesRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/investor-dashboard': typeof AuthenticatedInvestorDashboardRoute
  '/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/performance': typeof AuthenticatedPerformanceRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/runner-dashboard': typeof AuthenticatedRunnerDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/templates': typeof AuthenticatedTemplatesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/academy/$courseSlug': typeof AuthenticatedAcademyCourseSlugRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/background-checks': typeof AuthenticatedAdminBackgroundChecksRoute
  '/admin/broadcasts': typeof AuthenticatedAdminBroadcastsRoute
  '/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/admin/marketplace-health': typeof AuthenticatedAdminMarketplaceHealthRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/profiles': typeof AuthenticatedAdminProfilesRoute
  '/admin/runner-approvals': typeof AuthenticatedAdminRunnerApprovalsRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/investor': typeof AuthenticatedDashboardInvestorRoute
  '/dashboard/runner': typeof AuthenticatedDashboardRunnerRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/messages/new': typeof AuthenticatedMessagesNewRoute
  '/profile/background-check': typeof AuthenticatedProfileBackgroundCheckRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/id-verification': typeof AuthenticatedProfileIdVerificationRoute
  '/profile/verification': typeof AuthenticatedProfileVerificationRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/payments': typeof AuthenticatedSettingsPaymentsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/academy/': typeof AuthenticatedAcademyIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/academy/$courseSlug/$lessonSlug': typeof AuthenticatedAcademyCourseSlugLessonSlugRoute
  '/academy/$courseSlug/certificate': typeof AuthenticatedAcademyCourseSlugCertificateRoute
  '/academy/$courseSlug/quiz': typeof AuthenticatedAcademyCourseSlugQuizRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/academy/$courseSlug/': typeof AuthenticatedAcademyCourseSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/apply': typeof ApplyRoute
  '/auth-test': typeof AuthTestRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRouteWithChildren
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/disputes': typeof AuthenticatedDisputesRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/investor-dashboard': typeof AuthenticatedInvestorDashboardRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/runner-dashboard': typeof AuthenticatedRunnerDashboardRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/background-checks': typeof AuthenticatedAdminBackgroundChecksRoute
  '/admin/broadcasts': typeof AuthenticatedAdminBroadcastsRoute
  '/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/admin/marketplace-health': typeof AuthenticatedAdminMarketplaceHealthRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/profiles': typeof AuthenticatedAdminProfilesRoute
  '/admin/runner-approvals': typeof AuthenticatedAdminRunnerApprovalsRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/dashboard/investor': typeof AuthenticatedDashboardInvestorRoute
  '/dashboard/runner': typeof AuthenticatedDashboardRunnerRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/messages/new': typeof AuthenticatedMessagesNewRoute
  '/profile/background-check': typeof AuthenticatedProfileBackgroundCheckRoute
  '/profile/edit': typeof AuthenticatedProfileEditRoute
  '/profile/id-verification': typeof AuthenticatedProfileIdVerificationRoute
  '/profile/verification': typeof AuthenticatedProfileVerificationRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/payments': typeof AuthenticatedSettingsPaymentsRoute
  '/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/academy': typeof AuthenticatedAcademyIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/academy/$courseSlug/$lessonSlug': typeof AuthenticatedAcademyCourseSlugLessonSlugRoute
  '/academy/$courseSlug/certificate': typeof AuthenticatedAcademyCourseSlugCertificateRoute
  '/academy/$courseSlug/quiz': typeof AuthenticatedAcademyCourseSlugQuizRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/academy/$courseSlug': typeof AuthenticatedAcademyCourseSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/apply': typeof ApplyRoute
  '/auth-test': typeof AuthTestRoute
  '/faq': typeof FaqRoute
  '/investors': typeof InvestorsRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tasks': typeof TasksRouteWithChildren
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/_authenticated/academy': typeof AuthenticatedAcademyRouteWithChildren
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/disputes': typeof AuthenticatedDisputesRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/investor-dashboard': typeof AuthenticatedInvestorDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteWithChildren
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/runner-dashboard': typeof AuthenticatedRunnerDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/profile/$slug': typeof ProfileSlugRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/_authenticated/academy/$courseSlug': typeof AuthenticatedAcademyCourseSlugRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/background-checks': typeof AuthenticatedAdminBackgroundChecksRoute
  '/_authenticated/admin/broadcasts': typeof AuthenticatedAdminBroadcastsRoute
  '/_authenticated/admin/dispatch': typeof AuthenticatedAdminDispatchRoute
  '/_authenticated/admin/marketplace-health': typeof AuthenticatedAdminMarketplaceHealthRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/profiles': typeof AuthenticatedAdminProfilesRoute
  '/_authenticated/admin/runner-approvals': typeof AuthenticatedAdminRunnerApprovalsRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/dashboard/favorites': typeof AuthenticatedDashboardFavoritesRoute
  '/_authenticated/dashboard/investor': typeof AuthenticatedDashboardInvestorRoute
  '/_authenticated/dashboard/runner': typeof AuthenticatedDashboardRunnerRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/messages/new': typeof AuthenticatedMessagesNewRoute
  '/_authenticated/profile/background-check': typeof AuthenticatedProfileBackgroundCheckRoute
  '/_authenticated/profile/edit': typeof AuthenticatedProfileEditRoute
  '/_authenticated/profile/id-verification': typeof AuthenticatedProfileIdVerificationRoute
  '/_authenticated/profile/verification': typeof AuthenticatedProfileVerificationRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/admin': typeof AuthenticatedSettingsAdminRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/payments': typeof AuthenticatedSettingsPaymentsRoute
  '/_authenticated/settings/preferences': typeof AuthenticatedSettingsPreferencesRoute
  '/_authenticated/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/academy/': typeof AuthenticatedAcademyIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/academy/$courseSlug/$lessonSlug': typeof AuthenticatedAcademyCourseSlugLessonSlugRoute
  '/_authenticated/academy/$courseSlug/certificate': typeof AuthenticatedAcademyCourseSlugCertificateRoute
  '/_authenticated/academy/$courseSlug/quiz': typeof AuthenticatedAcademyCourseSlugQuizRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_authenticated/academy/$courseSlug/': typeof AuthenticatedAcademyCourseSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/apply'
    | '/auth-test'
    | '/faq'
    | '/investors'
    | '/login'
    | '/privacy'
    | '/profiles'
    | '/signup'
    | '/sitemap.xml'
    | '/tasks'
    | '/terms'
    | '/waitlist'
    | '/academy'
    | '/activity'
    | '/admin'
    | '/admin-dashboard'
    | '/applications'
    | '/billing'
    | '/disputes'
    | '/earnings'
    | '/investor-dashboard'
    | '/messages'
    | '/performance'
    | '/reviews'
    | '/runner-dashboard'
    | '/settings'
    | '/templates'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/profile/$slug'
    | '/tasks/$taskId'
    | '/academy/$courseSlug'
    | '/admin/analytics'
    | '/admin/background-checks'
    | '/admin/broadcasts'
    | '/admin/dispatch'
    | '/admin/marketplace-health'
    | '/admin/moderation'
    | '/admin/profiles'
    | '/admin/runner-approvals'
    | '/admin/verifications'
    | '/dashboard/favorites'
    | '/dashboard/investor'
    | '/dashboard/runner'
    | '/messages/$conversationId'
    | '/messages/new'
    | '/profile/background-check'
    | '/profile/edit'
    | '/profile/id-verification'
    | '/profile/verification'
    | '/settings/account'
    | '/settings/admin'
    | '/settings/notifications'
    | '/settings/payments'
    | '/settings/preferences'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/support'
    | '/lovable/email/suppression'
    | '/academy/'
    | '/admin/'
    | '/dashboard/'
    | '/messages/'
    | '/settings/'
    | '/academy/$courseSlug/$lessonSlug'
    | '/academy/$courseSlug/certificate'
    | '/academy/$courseSlug/quiz'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/academy/$courseSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/apply'
    | '/auth-test'
    | '/faq'
    | '/investors'
    | '/login'
    | '/privacy'
    | '/profiles'
    | '/signup'
    | '/sitemap.xml'
    | '/tasks'
    | '/terms'
    | '/waitlist'
    | '/activity'
    | '/admin-dashboard'
    | '/applications'
    | '/billing'
    | '/disputes'
    | '/earnings'
    | '/investor-dashboard'
    | '/performance'
    | '/reviews'
    | '/runner-dashboard'
    | '/templates'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/profile/$slug'
    | '/tasks/$taskId'
    | '/admin/analytics'
    | '/admin/background-checks'
    | '/admin/broadcasts'
    | '/admin/dispatch'
    | '/admin/marketplace-health'
    | '/admin/moderation'
    | '/admin/profiles'
    | '/admin/runner-approvals'
    | '/admin/verifications'
    | '/dashboard/favorites'
    | '/dashboard/investor'
    | '/dashboard/runner'
    | '/messages/$conversationId'
    | '/messages/new'
    | '/profile/background-check'
    | '/profile/edit'
    | '/profile/id-verification'
    | '/profile/verification'
    | '/settings/account'
    | '/settings/admin'
    | '/settings/notifications'
    | '/settings/payments'
    | '/settings/preferences'
    | '/settings/privacy'
    | '/settings/profile'
    | '/settings/security'
    | '/settings/support'
    | '/lovable/email/suppression'
    | '/academy'
    | '/admin'
    | '/dashboard'
    | '/messages'
    | '/settings'
    | '/academy/$courseSlug/$lessonSlug'
    | '/academy/$courseSlug/certificate'
    | '/academy/$courseSlug/quiz'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/academy/$courseSlug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authenticated'
    | '/apply'
    | '/auth-test'
    | '/faq'
    | '/investors'
    | '/login'
    | '/privacy'
    | '/profiles'
    | '/signup'
    | '/sitemap.xml'
    | '/tasks'
    | '/terms'
    | '/waitlist'
    | '/_authenticated/academy'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/admin-dashboard'
    | '/_authenticated/applications'
    | '/_authenticated/billing'
    | '/_authenticated/disputes'
    | '/_authenticated/earnings'
    | '/_authenticated/investor-dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/performance'
    | '/_authenticated/reviews'
    | '/_authenticated/runner-dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/checkout/return'
    | '/email/unsubscribe'
    | '/profile/$slug'
    | '/tasks/$taskId'
    | '/_authenticated/academy/$courseSlug'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/background-checks'
    | '/_authenticated/admin/broadcasts'
    | '/_authenticated/admin/dispatch'
    | '/_authenticated/admin/marketplace-health'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/profiles'
    | '/_authenticated/admin/runner-approvals'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/dashboard/favorites'
    | '/_authenticated/dashboard/investor'
    | '/_authenticated/dashboard/runner'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/messages/new'
    | '/_authenticated/profile/background-check'
    | '/_authenticated/profile/edit'
    | '/_authenticated/profile/id-verification'
    | '/_authenticated/profile/verification'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/admin'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/payments'
    | '/_authenticated/settings/preferences'
    | '/_authenticated/settings/privacy'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/security'
    | '/_authenticated/settings/support'
    | '/lovable/email/suppression'
    | '/_authenticated/academy/'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/messages/'
    | '/_authenticated/settings/'
    | '/_authenticated/academy/$courseSlug/$lessonSlug'
    | '/_authenticated/academy/$courseSlug/certificate'
    | '/_authenticated/academy/$courseSlug/quiz'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_authenticated/academy/$courseSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApplyRoute: typeof ApplyRoute
  AuthTestRoute: typeof AuthTestRoute
  FaqRoute: typeof FaqRoute
  InvestorsRoute: typeof InvestorsRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfilesRoute: typeof ProfilesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TasksRoute: typeof TasksRouteWithChildren
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ProfileSlugRoute: typeof ProfileSlugRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investors': {
      id: '/investors'
      path: '/investors'
      fullPath: '/investors'
      preLoaderRoute: typeof InvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-test': {
      id: '/auth-test'
      path: '/auth-test'
      fullPath: '/auth-test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof TasksRoute
    }
    '/profile/$slug': {
      id: '/profile/$slug'
      path: '/profile/$slug'
      fullPath: '/profile/$slug'
      preLoaderRoute: typeof ProfileSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/runner-dashboard': {
      id: '/_authenticated/runner-dashboard'
      path: '/runner-dashboard'
      fullPath: '/runner-dashboard'
      preLoaderRoute: typeof AuthenticatedRunnerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/investor-dashboard': {
      id: '/_authenticated/investor-dashboard'
      path: '/investor-dashboard'
      fullPath: '/investor-dashboard'
      preLoaderRoute: typeof AuthenticatedInvestorDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/disputes': {
      id: '/_authenticated/disputes'
      path: '/disputes'
      fullPath: '/disputes'
      preLoaderRoute: typeof AuthenticatedDisputesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin-dashboard': {
      id: '/_authenticated/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/academy': {
      id: '/_authenticated/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AuthenticatedAcademyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/academy/': {
      id: '/_authenticated/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AuthenticatedAcademyIndexRouteImport
      parentRoute: typeof AuthenticatedAcademyRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/support': {
      id: '/_authenticated/settings/support'
      path: '/support'
      fullPath: '/settings/support'
      preLoaderRoute: typeof AuthenticatedSettingsSupportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/privacy': {
      id: '/_authenticated/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthenticatedSettingsPrivacyRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/preferences': {
      id: '/_authenticated/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof AuthenticatedSettingsPreferencesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/payments': {
      id: '/_authenticated/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AuthenticatedSettingsPaymentsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/admin': {
      id: '/_authenticated/settings/admin'
      path: '/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof AuthenticatedSettingsAdminRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/profile/verification': {
      id: '/_authenticated/profile/verification'
      path: '/profile/verification'
      fullPath: '/profile/verification'
      preLoaderRoute: typeof AuthenticatedProfileVerificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/id-verification': {
      id: '/_authenticated/profile/id-verification'
      path: '/profile/id-verification'
      fullPath: '/profile/id-verification'
      preLoaderRoute: typeof AuthenticatedProfileIdVerificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/edit': {
      id: '/_authenticated/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthenticatedProfileEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/background-check': {
      id: '/_authenticated/profile/background-check'
      path: '/profile/background-check'
      fullPath: '/profile/background-check'
      preLoaderRoute: typeof AuthenticatedProfileBackgroundCheckRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/new': {
      id: '/_authenticated/messages/new'
      path: '/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof AuthenticatedMessagesNewRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedMessagesRoute
    }
    '/_authenticated/dashboard/runner': {
      id: '/_authenticated/dashboard/runner'
      path: '/dashboard/runner'
      fullPath: '/dashboard/runner'
      preLoaderRoute: typeof AuthenticatedDashboardRunnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/investor': {
      id: '/_authenticated/dashboard/investor'
      path: '/dashboard/investor'
      fullPath: '/dashboard/investor'
      preLoaderRoute: typeof AuthenticatedDashboardInvestorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/favorites': {
      id: '/_authenticated/dashboard/favorites'
      path: '/dashboard/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof AuthenticatedDashboardFavoritesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/runner-approvals': {
      id: '/_authenticated/admin/runner-approvals'
      path: '/runner-approvals'
      fullPath: '/admin/runner-approvals'
      preLoaderRoute: typeof AuthenticatedAdminRunnerApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profiles': {
      id: '/_authenticated/admin/profiles'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AuthenticatedAdminProfilesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/marketplace-health': {
      id: '/_authenticated/admin/marketplace-health'
      path: '/marketplace-health'
      fullPath: '/admin/marketplace-health'
      preLoaderRoute: typeof AuthenticatedAdminMarketplaceHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dispatch': {
      id: '/_authenticated/admin/dispatch'
      path: '/dispatch'
      fullPath: '/admin/dispatch'
      preLoaderRoute: typeof AuthenticatedAdminDispatchRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/broadcasts': {
      id: '/_authenticated/admin/broadcasts'
      path: '/broadcasts'
      fullPath: '/admin/broadcasts'
      preLoaderRoute: typeof AuthenticatedAdminBroadcastsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/background-checks': {
      id: '/_authenticated/admin/background-checks'
      path: '/background-checks'
      fullPath: '/admin/background-checks'
      preLoaderRoute: typeof AuthenticatedAdminBackgroundChecksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/academy/$courseSlug': {
      id: '/_authenticated/academy/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/academy/$courseSlug'
      preLoaderRoute: typeof AuthenticatedAcademyCourseSlugRouteImport
      parentRoute: typeof AuthenticatedAcademyRoute
    }
    '/_authenticated/academy/$courseSlug/': {
      id: '/_authenticated/academy/$courseSlug/'
      path: '/'
      fullPath: '/academy/$courseSlug/'
      preLoaderRoute: typeof AuthenticatedAcademyCourseSlugIndexRouteImport
      parentRoute: typeof AuthenticatedAcademyCourseSlugRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/academy/$courseSlug/quiz': {
      id: '/_authenticated/academy/$courseSlug/quiz'
      path: '/quiz'
      fullPath: '/academy/$courseSlug/quiz'
      preLoaderRoute: typeof AuthenticatedAcademyCourseSlugQuizRouteImport
      parentRoute: typeof AuthenticatedAcademyCourseSlugRoute
    }
    '/_authenticated/academy/$courseSlug/certificate': {
      id: '/_authenticated/academy/$courseSlug/certificate'
      path: '/certificate'
      fullPath: '/academy/$courseSlug/certificate'
      preLoaderRoute: typeof AuthenticatedAcademyCourseSlugCertificateRouteImport
      parentRoute: typeof AuthenticatedAcademyCourseSlugRoute
    }
    '/_authenticated/academy/$courseSlug/$lessonSlug': {
      id: '/_authenticated/academy/$courseSlug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/academy/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof AuthenticatedAcademyCourseSlugLessonSlugRouteImport
      parentRoute: typeof AuthenticatedAcademyCourseSlugRoute
    }
  }
}

interface AuthenticatedAcademyCourseSlugRouteChildren {
  AuthenticatedAcademyCourseSlugLessonSlugRoute: typeof AuthenticatedAcademyCourseSlugLessonSlugRoute
  AuthenticatedAcademyCourseSlugCertificateRoute: typeof AuthenticatedAcademyCourseSlugCertificateRoute
  AuthenticatedAcademyCourseSlugQuizRoute: typeof AuthenticatedAcademyCourseSlugQuizRoute
  AuthenticatedAcademyCourseSlugIndexRoute: typeof AuthenticatedAcademyCourseSlugIndexRoute
}

const AuthenticatedAcademyCourseSlugRouteChildren: AuthenticatedAcademyCourseSlugRouteChildren =
  {
    AuthenticatedAcademyCourseSlugLessonSlugRoute:
      AuthenticatedAcademyCourseSlugLessonSlugRoute,
    AuthenticatedAcademyCourseSlugCertificateRoute:
      AuthenticatedAcademyCourseSlugCertificateRoute,
    AuthenticatedAcademyCourseSlugQuizRoute:
      AuthenticatedAcademyCourseSlugQuizRoute,
    AuthenticatedAcademyCourseSlugIndexRoute:
      AuthenticatedAcademyCourseSlugIndexRoute,
  }

const AuthenticatedAcademyCourseSlugRouteWithChildren =
  AuthenticatedAcademyCourseSlugRoute._addFileChildren(
    AuthenticatedAcademyCourseSlugRouteChildren,
  )

interface AuthenticatedAcademyRouteChildren {
  AuthenticatedAcademyCourseSlugRoute: typeof AuthenticatedAcademyCourseSlugRouteWithChildren
  AuthenticatedAcademyIndexRoute: typeof AuthenticatedAcademyIndexRoute
}

const AuthenticatedAcademyRouteChildren: AuthenticatedAcademyRouteChildren = {
  AuthenticatedAcademyCourseSlugRoute:
    AuthenticatedAcademyCourseSlugRouteWithChildren,
  AuthenticatedAcademyIndexRoute: AuthenticatedAcademyIndexRoute,
}

const AuthenticatedAcademyRouteWithChildren =
  AuthenticatedAcademyRoute._addFileChildren(AuthenticatedAcademyRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBackgroundChecksRoute: typeof AuthenticatedAdminBackgroundChecksRoute
  AuthenticatedAdminBroadcastsRoute: typeof AuthenticatedAdminBroadcastsRoute
  AuthenticatedAdminDispatchRoute: typeof AuthenticatedAdminDispatchRoute
  AuthenticatedAdminMarketplaceHealthRoute: typeof AuthenticatedAdminMarketplaceHealthRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminProfilesRoute: typeof AuthenticatedAdminProfilesRoute
  AuthenticatedAdminRunnerApprovalsRoute: typeof AuthenticatedAdminRunnerApprovalsRoute
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminBackgroundChecksRoute:
    AuthenticatedAdminBackgroundChecksRoute,
  AuthenticatedAdminBroadcastsRoute: AuthenticatedAdminBroadcastsRoute,
  AuthenticatedAdminDispatchRoute: AuthenticatedAdminDispatchRoute,
  AuthenticatedAdminMarketplaceHealthRoute:
    AuthenticatedAdminMarketplaceHealthRoute,
  AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
  AuthenticatedAdminProfilesRoute: AuthenticatedAdminProfilesRoute,
  AuthenticatedAdminRunnerApprovalsRoute:
    AuthenticatedAdminRunnerApprovalsRoute,
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedMessagesRouteChildren {
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedMessagesNewRoute: typeof AuthenticatedMessagesNewRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedMessagesRouteChildren: AuthenticatedMessagesRouteChildren = {
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedMessagesNewRoute: AuthenticatedMessagesNewRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedMessagesRouteWithChildren =
  AuthenticatedMessagesRoute._addFileChildren(
    AuthenticatedMessagesRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAdminRoute: typeof AuthenticatedSettingsAdminRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsPaymentsRoute: typeof AuthenticatedSettingsPaymentsRoute
  AuthenticatedSettingsPreferencesRoute: typeof AuthenticatedSettingsPreferencesRoute
  AuthenticatedSettingsPrivacyRoute: typeof AuthenticatedSettingsPrivacyRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsSupportRoute: typeof AuthenticatedSettingsSupportRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsAdminRoute: AuthenticatedSettingsAdminRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsPaymentsRoute: AuthenticatedSettingsPaymentsRoute,
  AuthenticatedSettingsPreferencesRoute: AuthenticatedSettingsPreferencesRoute,
  AuthenticatedSettingsPrivacyRoute: AuthenticatedSettingsPrivacyRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedSettingsSupportRoute: AuthenticatedSettingsSupportRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAcademyRoute: typeof AuthenticatedAcademyRouteWithChildren
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDisputesRoute: typeof AuthenticatedDisputesRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedInvestorDashboardRoute: typeof AuthenticatedInvestorDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRouteWithChildren
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedRunnerDashboardRoute: typeof AuthenticatedRunnerDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedDashboardFavoritesRoute: typeof AuthenticatedDashboardFavoritesRoute
  AuthenticatedDashboardInvestorRoute: typeof AuthenticatedDashboardInvestorRoute
  AuthenticatedDashboardRunnerRoute: typeof AuthenticatedDashboardRunnerRoute
  AuthenticatedProfileBackgroundCheckRoute: typeof AuthenticatedProfileBackgroundCheckRoute
  AuthenticatedProfileEditRoute: typeof AuthenticatedProfileEditRoute
  AuthenticatedProfileIdVerificationRoute: typeof AuthenticatedProfileIdVerificationRoute
  AuthenticatedProfileVerificationRoute: typeof AuthenticatedProfileVerificationRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAcademyRoute: AuthenticatedAcademyRouteWithChildren,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDisputesRoute: AuthenticatedDisputesRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedInvestorDashboardRoute: AuthenticatedInvestorDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRouteWithChildren,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedRunnerDashboardRoute: AuthenticatedRunnerDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedDashboardFavoritesRoute: AuthenticatedDashboardFavoritesRoute,
  AuthenticatedDashboardInvestorRoute: AuthenticatedDashboardInvestorRoute,
  AuthenticatedDashboardRunnerRoute: AuthenticatedDashboardRunnerRoute,
  AuthenticatedProfileBackgroundCheckRoute:
    AuthenticatedProfileBackgroundCheckRoute,
  AuthenticatedProfileEditRoute: AuthenticatedProfileEditRoute,
  AuthenticatedProfileIdVerificationRoute:
    AuthenticatedProfileIdVerificationRoute,
  AuthenticatedProfileVerificationRoute: AuthenticatedProfileVerificationRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface TasksRouteChildren {
  TasksTaskIdRoute: typeof TasksTaskIdRoute
}

const TasksRouteChildren: TasksRouteChildren = {
  TasksTaskIdRoute: TasksTaskIdRoute,
}

const TasksRouteWithChildren = TasksRoute._addFileChildren(TasksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApplyRoute: ApplyRoute,
  AuthTestRoute: AuthTestRoute,
  FaqRoute: FaqRoute,
  InvestorsRoute: InvestorsRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProfilesRoute: ProfilesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TasksRoute: TasksRouteWithChildren,
  TermsRoute: TermsRoute,
  WaitlistRoute: WaitlistRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ProfileSlugRoute: ProfileSlugRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
